<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>408691b8-7973-4bad-bc27-7f46e9aa39d8</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
		<PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TicketingSystem.Application\TicketingSystem.Application.csproj" />
		<ProjectReference Include="..\TicketingSystem.Domain\TicketingSystem.Domain.csproj" />
		<ProjectReference Include="..\TicketingSystem.Infrastructure\TicketingSystem.Infrastructure.csproj" />
	</ItemGroup>

</Project>
